/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cpkobwzniaewvwbwwksk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwa29id3puaWFld3Z3Ynd3a3NrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcxNzUyNjksImV4cCI6MjEwMjc1MTI2OX0.sZjbDAxE--jIaCv3MvqTXrY1B--mRhpDHun9dVHk068"